# Generated by Django 3.1.2 on 2020-10-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photography', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Photography',
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Resolution',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_camera', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'TypeOfCamera',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pricing/')),
                ('photography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_photography', to='pricing.photography')),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_photos', to='pricing.photography')),
                ('processing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_processing', to='pricing.photography')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_resolution', to='pricing.photography')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_term', to='pricing.photography')),
                ('type_of_camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_typeofcameray', to='pricing.photography')),
            ],
            options={
                'verbose_name_plural': 'Pricing',
            },
        ),
    ]
