# Generated by Django 3.1.2 on 2020-10-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20201017_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='term',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
